name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Cache pipenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run scrapper
        run: |
          pipenv run python main.py -l error

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: Y.MM.DD.HH.mm

      - name: Create info file
        run: |
          echo '{ "updated": "${{ steps.current-time.outputs.time }}" }' > info.json

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: "${{ steps.current-time.outputs.formattedTime }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.current-time.outputs.formattedTime }}"
          body: "${{ steps.current-time.outputs.time }}"
          files: |
            ./info.json
            ./words.json
        env:
          GITHUB_REPOSITORY: kevinrpb/additives-scrapper
